// <auto-generated />
using System.Collections.Generic;
using Atlas.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Api.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    partial class AtlasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Api.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ord")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Who")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("Atlas.Api.Blocker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Blockers");
                });

            modelBuilder.Entity("Atlas.Api.BudgetSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<int>>("Actual")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Allocated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Months")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<int>>("Planned")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Spent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpentPct")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BudgetSnapshots");
                });

            modelBuilder.Entity("Atlas.Api.DashboardKpi", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Delta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Good")
                        .HasColumnType("boolean");

                    b.Property<int>("Ord")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Spark")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("DashboardKpis");
                });

            modelBuilder.Entity("Atlas.Api.DeliveryReport", b =>
                {
                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<int>("BlockersCleared")
                        .HasColumnType("integer");

                    b.Property<int>("BlockersOpen")
                        .HasColumnType("integer");

                    b.Property<string>("BudgetBurn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<string>("CostPerDeliverable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InProgress")
                        .HasColumnType("integer");

                    b.Property<int>("Milestones")
                        .HasColumnType("integer");

                    b.Property<int>("OnTime")
                        .HasColumnType("integer");

                    b.Property<int>("Planned")
                        .HasColumnType("integer");

                    b.Property<string>("Satisfaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpendPct")
                        .HasColumnType("integer");

                    b.Property<string>("ValuePerEuro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VelTrend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Velocity")
                        .HasColumnType("integer");

                    b.HasKey("Period");

                    b.ToTable("DeliveryReports");
                });

            modelBuilder.Entity("Atlas.Api.Demand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Effort")
                        .HasColumnType("integer");

                    b.Property<bool>("Mine")
                        .HasColumnType("boolean");

                    b.Property<bool>("PendingApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("Atlas.Api.KeyResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectiveId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("KeyResults");
                });

            modelBuilder.Entity("Atlas.Api.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ord")
                        .HasColumnType("integer");

                    b.Property<string>("Sprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MyTasks");
                });

            modelBuilder.Entity("Atlas.Api.Objective", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Atlas.Api.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Projects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Releases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Atlas.Api.ProductMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Alloc")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMembers");
                });

            modelBuilder.Entity("Atlas.Api.ProductTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateIso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MappedRelease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTasks");
                });

            modelBuilder.Entity("Atlas.Api.Program", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Projects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Spent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Atlas.Api.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AttentionReason")
                        .HasColumnType("text");

                    b.Property<string>("AttentionSeverity")
                        .HasColumnType("text");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Capex")
                        .HasColumnType("numeric");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Due")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Forecast")
                        .HasColumnType("numeric");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LaborArch")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LaborDev")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LaborInfra")
                        .HasColumnType("numeric");

                    b.Property<string>("Methodology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<decimal>("Roi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Spent")
                        .HasColumnType("numeric");

                    b.Property<bool>("StakeholderVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Atlas.Api.Release", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Crs")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Env")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("Reqs")
                        .HasColumnType("integer");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Atlas.Api.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OpsPct")
                        .HasColumnType("integer");

                    b.Property<bool>("Over")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductPct")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectPct")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Atlas.Api.Blocker", b =>
                {
                    b.HasOne("Atlas.Api.Project", "Project")
                        .WithMany("Blockers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Atlas.Api.KeyResult", b =>
                {
                    b.HasOne("Atlas.Api.Objective", null)
                        .WithMany("Krs")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Api.ProductMember", b =>
                {
                    b.HasOne("Atlas.Api.Product", null)
                        .WithMany("Members")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Api.ProductTask", b =>
                {
                    b.HasOne("Atlas.Api.Product", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Api.Objective", b =>
                {
                    b.Navigation("Krs");
                });

            modelBuilder.Entity("Atlas.Api.Product", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Atlas.Api.Project", b =>
                {
                    b.Navigation("Blockers");
                });
#pragma warning restore 612, 618
        }
    }
}
